name: "sogetec"
services:
  env-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "8085:18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  postgres:
    image: "docker.io/library/postgres:18.3"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose:
      - "5432"
    networks:
      - "aspire"
  keycloak:
    image: "quay.io/keycloak/keycloak:26.6"
    pull_policy: "always"
    command:
      - "start"
      - "--import-realm"
      - "--health-enabled=true"
      - "--db=Aspire.Hosting.DistributedApplicationResourceBuilder`1[Aspire.Hosting.ApplicationModel.ParameterResource]"
      - "--db-url=Aspire.Hosting.DistributedApplicationResourceBuilder`1[Aspire.Hosting.ApplicationModel.ParameterResource]"
      - "--db-username=Aspire.Hosting.DistributedApplicationResourceBuilder`1[Aspire.Hosting.ApplicationModel.ParameterResource]"
      - "--db-password=Aspire.Hosting.DistributedApplicationResourceBuilder`1[Aspire.Hosting.ApplicationModel.ParameterResource]"
      - "--hostname=Aspire.Hosting.DistributedApplicationResourceBuilder`1[Aspire.Hosting.ApplicationModel.ParameterResource]"
      - "--hostname-protocol=https"
      - "--https-certificate-file=/opt/keycloak/certs/tls.crt"
      - "--https-certificate-key-file=/opt/keycloak/certs/tls.key"
      - "--proxy=edge"
      - "--features=token-exchange,admin-fine-grained-authz"
      - "--spi-events-listener-jboss-logging-success-level=info"
      - "--spi-events-listener-jboss-logging-error-level=warn"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "${KEYCLOAK_PASSWORD}"
      KC_HEALTH_ENABLED: "true"
      KC_FEATURES: "opentelemetry"
      REALM_NAME: "sogetec"
      REALM_DISPLAY_NAME: "Sogetec"
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: "xforwarded"
      KC_HOSTNAME_STRICT: "false"
      CLIENT_SOGETEC_API_ID: "sogetec-api"
      CLIENT_SOGETEC_API_NAME: "Sogetec-api API"
      CLIENT_SOGETEC_API_SECRET: "${SOGETEC_API_SECRET}"
      CLIENT_SOGETEC_FRONTEND_ID: "sogetec-frontend"
      CLIENT_SOGETEC_FRONTEND_NAME: "Sogetec-frontend APP"
      CLIENT_SOGETEC_ADMIN_ID: "sogetec-admin"
      CLIENT_SOGETEC_ADMIN_NAME: "Sogetec-admin APP"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "keycloak"
    ports:
      - "8080"
      - "9000"
    volumes:
      - type: "volume"
        target: "/opt/keycloak/data"
        source: "sogetec.apphost-8ba8e719d3-keycloak-data"
        read_only: false
      - type: "bind"
        target: "/opt/keycloak/data/import"
        source: "${KEYCLOAK_BINDMOUNT_0}"
        read_only: true
      - type: "bind"
        target: "/opt/keycloak/realm-import/"
        source: "${KEYCLOAK_BINDMOUNT_1}"
        read_only: true
    networks:
      - "aspire"
  sogetec-api:
    image: "${SOGETEC_API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${SOGETEC_API_PORT}"
      ConnectionStrings__sogetecdb: "${SOGETECDB}"
      ConnectionStrings__redis: "${REDIS}"
      KEYCLOAK_HTTP: "http://keycloak:8080"
      services__keycloak__http__0: "http://keycloak:8080"
      Identity__Realm: "sogetec"
      Identity__ClientId: "sogetec-api"
      Identity__ClientSecret: "${SOGETEC_API_SECRET}"
      Cors__Origins__0: "${SOGETEC_SPA_URL}"
      Cors__Origins__1: "${SOGETEC_ADMIN_URL}"
      Cors__AllowCredentials: "true"
      Cors__Headers__0: "Content-Type"
      Cors__Headers__1: "Authorization"
      Cors__Headers__2: "Accept"
      Cors__Headers__3: "Origin"
      Cors__Headers__4: "X-Requested-With"
      Cors__Headers__5: "X-Powered-By"
      Cors__Headers__6: "x-request-id"
      Cors__Methods__0: "GET"
      Cors__Methods__1: "POST"
      Cors__Methods__2: "PUT"
      Cors__Methods__3: "DELETE"
      Cors__Methods__4: "PATCH"
      Cors__Methods__5: "OPTIONS"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "sogetec-api"
    expose:
      - "${SOGETEC_API_PORT}"
    depends_on:
      keycloak:
        condition: "service_started"
    networks:
      - "aspire"
  sogetec-frontend:
    image: "${SOGETEC_FRONTEND_IMAGE}"
    environment:
      NODE_ENV: "production"
      PORT: "3000"
      SOGETEC_API_HTTP: "http://sogetec-api:${SOGETEC_API_PORT}"
      services__sogetec-api__http__0: "http://sogetec-api:${SOGETEC_API_PORT}"
      SOGETEC_API_HTTPS: "https://sogetec-api:${SOGETEC_API_PORT}"
      VITE_SOGETEC_API_HTTPS: "https://sogetec-api:${SOGETEC_API_PORT}"
      VITE_SOGETEC_API_HTTP: "http://sogetec-api:${SOGETEC_API_PORT}"
      KEYCLOAK_HTTP: "http://keycloak:8080"
      services__keycloak__http__0: "http://keycloak:8080"
      VITE_KEYCLOAK_HTTP: "http://keycloak:8080"
      VITE_KEYCLOAK_REALM: "sogetec"
      VITE_KEYCLOAK_CLIENT_ID: "sogetec-frontend"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "sogetec-frontend"
    ports:
      - "8000"
      - "3000:3000"
    depends_on:
      sogetec-api:
        condition: "service_started"
      keycloak:
        condition: "service_started"
    networks:
      - "aspire"
  sogetec-admin:
    image: "${SOGETEC_ADMIN_IMAGE}"
    environment:
      NODE_ENV: "production"
      PORT: "3001"
      SOGETEC_API_HTTP: "http://sogetec-api:${SOGETEC_API_PORT}"
      services__sogetec-api__http__0: "http://sogetec-api:${SOGETEC_API_PORT}"
      SOGETEC_API_HTTPS: "https://sogetec-api:${SOGETEC_API_PORT}"
      VITE_SOGETEC_API_HTTPS: "https://sogetec-api:${SOGETEC_API_PORT}"
      VITE_SOGETEC_API_HTTP: "http://sogetec-api:${SOGETEC_API_PORT}"
      KEYCLOAK_HTTP: "http://keycloak:8080"
      services__keycloak__http__0: "http://keycloak:8080"
      VITE_KEYCLOAK_HTTP: "http://keycloak:8080"
      VITE_KEYCLOAK_REALM: "sogetec"
      VITE_KEYCLOAK_CLIENT_ID: "sogetec-admin"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "sogetec-admin"
    ports:
      - "8001"
      - "3001:3001"
    depends_on:
      sogetec-api:
        condition: "service_started"
      keycloak:
        condition: "service_started"
    networks:
      - "aspire"
  gateway:
    image: "mcr.microsoft.com/dotnet/nightly/yarp:2.3-preview"
    command:
      - "/app/yarp.dll"
    entrypoint:
      - "dotnet"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      SOGETEC_API_HTTP: "http://sogetec-api:${SOGETEC_API_PORT}"
      REVERSEPROXY__ROUTES__route0__MATCH__HOSTS__0: "api.sogetecsarl.com"
      REVERSEPROXY__ROUTES__route0__MATCH__PATH: "/{**catchall}"
      REVERSEPROXY__ROUTES__route0__CLUSTERID: "cluster_sogetec-api"
      REVERSEPROXY__ROUTES__route0__MAXREQUESTBODYSIZE: "10485760"
      REVERSEPROXY__ROUTES__route0__TRANSFORMS__0__Forwarded: "For,By,Host,Proto"
      REVERSEPROXY__ROUTES__route0__TRANSFORMS__0__Action: "Set"
      REVERSEPROXY__ROUTES__route0__TRANSFORMS__0__ForFormat: "Random"
      REVERSEPROXY__ROUTES__route0__TRANSFORMS__0__ByFormat: "Random"
      REVERSEPROXY__ROUTES__route0__TRANSFORMS__1__RequestHeader: "X-Forwarded-Proto"
      REVERSEPROXY__ROUTES__route0__TRANSFORMS__1__Set: "https"
      REVERSEPROXY__ROUTES__route0__TRANSFORMS__2__RequestHeader: "X-Real-IP"
      REVERSEPROXY__ROUTES__route0__TRANSFORMS__2__Append: "{RemoteIpAddress}"
      REVERSEPROXY__ROUTES__route0__TRANSFORMS__3__ResponseHeader: "X-Powered-By"
      REVERSEPROXY__ROUTES__route0__TRANSFORMS__3__Append: "Sogetec Gateway"
      REVERSEPROXY__ROUTES__route0__TRANSFORMS__3__When: "Success"
      REVERSEPROXY__ROUTES__route1__MATCH__HOSTS__0: "admin.sogetecsarl.com"
      REVERSEPROXY__ROUTES__route1__MATCH__PATH: "/{**catchall}"
      REVERSEPROXY__ROUTES__route1__CLUSTERID: "cluster_sogetec-admin"
      REVERSEPROXY__ROUTES__route1__MAXREQUESTBODYSIZE: "10485760"
      REVERSEPROXY__ROUTES__route1__TRANSFORMS__0__Forwarded: "For,By,Host,Proto"
      REVERSEPROXY__ROUTES__route1__TRANSFORMS__0__Action: "Set"
      REVERSEPROXY__ROUTES__route1__TRANSFORMS__0__ForFormat: "Random"
      REVERSEPROXY__ROUTES__route1__TRANSFORMS__0__ByFormat: "Random"
      REVERSEPROXY__ROUTES__route1__TRANSFORMS__1__RequestHeader: "X-Forwarded-Proto"
      REVERSEPROXY__ROUTES__route1__TRANSFORMS__1__Set: "https"
      REVERSEPROXY__ROUTES__route1__TRANSFORMS__2__RequestHeader: "X-Real-IP"
      REVERSEPROXY__ROUTES__route1__TRANSFORMS__2__Append: "{RemoteIpAddress}"
      REVERSEPROXY__ROUTES__route1__TRANSFORMS__3__ResponseHeader: "X-Powered-By"
      REVERSEPROXY__ROUTES__route1__TRANSFORMS__3__Append: "Sogetec Gateway"
      REVERSEPROXY__ROUTES__route1__TRANSFORMS__3__When: "Success"
      REVERSEPROXY__ROUTES__route2__MATCH__HOSTS__0: "sogetecsarl.com"
      REVERSEPROXY__ROUTES__route2__MATCH__PATH: "/{**catchall}"
      REVERSEPROXY__ROUTES__route2__ORDER: "100"
      REVERSEPROXY__ROUTES__route2__CLUSTERID: "cluster_sogetec-frontend"
      REVERSEPROXY__ROUTES__route2__MAXREQUESTBODYSIZE: "10485760"
      REVERSEPROXY__ROUTES__route2__TRANSFORMS__0__Forwarded: "For,By,Host,Proto"
      REVERSEPROXY__ROUTES__route2__TRANSFORMS__0__Action: "Set"
      REVERSEPROXY__ROUTES__route2__TRANSFORMS__0__ForFormat: "Random"
      REVERSEPROXY__ROUTES__route2__TRANSFORMS__0__ByFormat: "Random"
      REVERSEPROXY__ROUTES__route2__TRANSFORMS__1__RequestHeader: "X-Forwarded-Proto"
      REVERSEPROXY__ROUTES__route2__TRANSFORMS__1__Set: "https"
      REVERSEPROXY__ROUTES__route2__TRANSFORMS__2__RequestHeader: "X-Forwarded-Host"
      REVERSEPROXY__ROUTES__route2__TRANSFORMS__2__Append: "{Host}"
      REVERSEPROXY__ROUTES__route2__TRANSFORMS__3__ResponseHeader: "X-Powered-By"
      REVERSEPROXY__ROUTES__route2__TRANSFORMS__3__Append: "Sogetec Gateway"
      REVERSEPROXY__ROUTES__route2__TRANSFORMS__3__When: "Success"
      REVERSEPROXY__ROUTES__route3__MATCH__HOSTS__0: "identity.Sogetec.com"
      REVERSEPROXY__ROUTES__route3__MATCH__PATH: "/{**catchall}"
      REVERSEPROXY__ROUTES__route3__CLUSTERID: "cluster_keycloak"
      REVERSEPROXY__ROUTES__route3__MAXREQUESTBODYSIZE: "10485760"
      REVERSEPROXY__ROUTES__route3__TRANSFORMS__0__Forwarded: "For,By,Host,Proto"
      REVERSEPROXY__ROUTES__route3__TRANSFORMS__0__Action: "Set"
      REVERSEPROXY__ROUTES__route3__TRANSFORMS__0__ForFormat: "Random"
      REVERSEPROXY__ROUTES__route3__TRANSFORMS__0__ByFormat: "Random"
      REVERSEPROXY__ROUTES__route3__TRANSFORMS__1__RequestHeader: "X-Forwarded-Proto"
      REVERSEPROXY__ROUTES__route3__TRANSFORMS__1__Set: "https"
      REVERSEPROXY__ROUTES__route3__TRANSFORMS__2__ResponseHeader: "X-Powered-By"
      REVERSEPROXY__ROUTES__route3__TRANSFORMS__2__Append: "Sogetec Gateway"
      REVERSEPROXY__ROUTES__route3__TRANSFORMS__2__When: "Success"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__LOADBALANCINGPOLICY: "RoundRobin"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__ENABLED: "True"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__INTERVAL__TICKS: "100000000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__INTERVAL__DAYS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__INTERVAL__HOURS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__INTERVAL__MILLISECONDS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__INTERVAL__MICROSECONDS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__INTERVAL__NANOSECONDS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__INTERVAL__MINUTES: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__INTERVAL__SECONDS: "10"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__INTERVAL__TOTALDAYS: "0.00011574074074074075"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__INTERVAL__TOTALHOURS: "0.002777777777777778"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__INTERVAL__TOTALMILLISECONDS: "10000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__INTERVAL__TOTALMICROSECONDS: "10000000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__INTERVAL__TOTALNANOSECONDS: "10000000000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__INTERVAL__TOTALMINUTES: "0.16666666666666666"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__INTERVAL__TOTALSECONDS: "10"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__TIMEOUT__TICKS: "50000000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__TIMEOUT__DAYS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__TIMEOUT__HOURS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__TIMEOUT__MILLISECONDS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__TIMEOUT__MICROSECONDS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__TIMEOUT__NANOSECONDS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__TIMEOUT__MINUTES: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__TIMEOUT__SECONDS: "5"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALDAYS: "5.787037037037037E-05"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALHOURS: "0.001388888888888889"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALMILLISECONDS: "5000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALMICROSECONDS: "5000000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALNANOSECONDS: "5000000000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALMINUTES: "0.08333333333333333"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALSECONDS: "5"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__POLICY: "ConsecutiveFailures"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__HEALTHCHECK__ACTIVE__PATH: "/health"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-api__DESTINATIONS__destination1__ADDRESS: "https+http://sogetec-api"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__LOADBALANCINGPOLICY: "RoundRobin"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__ENABLED: "True"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__INTERVAL__TICKS: "100000000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__INTERVAL__DAYS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__INTERVAL__HOURS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__INTERVAL__MILLISECONDS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__INTERVAL__MICROSECONDS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__INTERVAL__NANOSECONDS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__INTERVAL__MINUTES: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__INTERVAL__SECONDS: "10"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__INTERVAL__TOTALDAYS: "0.00011574074074074075"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__INTERVAL__TOTALHOURS: "0.002777777777777778"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__INTERVAL__TOTALMILLISECONDS: "10000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__INTERVAL__TOTALMICROSECONDS: "10000000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__INTERVAL__TOTALNANOSECONDS: "10000000000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__INTERVAL__TOTALMINUTES: "0.16666666666666666"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__INTERVAL__TOTALSECONDS: "10"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__TIMEOUT__TICKS: "50000000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__TIMEOUT__DAYS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__TIMEOUT__HOURS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__TIMEOUT__MILLISECONDS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__TIMEOUT__MICROSECONDS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__TIMEOUT__NANOSECONDS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__TIMEOUT__MINUTES: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__TIMEOUT__SECONDS: "5"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALDAYS: "5.787037037037037E-05"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALHOURS: "0.001388888888888889"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALMILLISECONDS: "5000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALMICROSECONDS: "5000000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALNANOSECONDS: "5000000000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALMINUTES: "0.08333333333333333"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALSECONDS: "5"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__POLICY: "ConsecutiveFailures"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__HEALTHCHECK__ACTIVE__PATH: "/health"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-frontend__DESTINATIONS__destination1__ADDRESS: "https+http://sogetec-frontend"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__LOADBALANCINGPOLICY: "RoundRobin"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__ENABLED: "True"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__INTERVAL__TICKS: "100000000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__INTERVAL__DAYS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__INTERVAL__HOURS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__INTERVAL__MILLISECONDS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__INTERVAL__MICROSECONDS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__INTERVAL__NANOSECONDS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__INTERVAL__MINUTES: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__INTERVAL__SECONDS: "10"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__INTERVAL__TOTALDAYS: "0.00011574074074074075"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__INTERVAL__TOTALHOURS: "0.002777777777777778"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__INTERVAL__TOTALMILLISECONDS: "10000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__INTERVAL__TOTALMICROSECONDS: "10000000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__INTERVAL__TOTALNANOSECONDS: "10000000000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__INTERVAL__TOTALMINUTES: "0.16666666666666666"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__INTERVAL__TOTALSECONDS: "10"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__TIMEOUT__TICKS: "50000000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__TIMEOUT__DAYS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__TIMEOUT__HOURS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__TIMEOUT__MILLISECONDS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__TIMEOUT__MICROSECONDS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__TIMEOUT__NANOSECONDS: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__TIMEOUT__MINUTES: "0"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__TIMEOUT__SECONDS: "5"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALDAYS: "5.787037037037037E-05"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALHOURS: "0.001388888888888889"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALMILLISECONDS: "5000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALMICROSECONDS: "5000000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALNANOSECONDS: "5000000000"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALMINUTES: "0.08333333333333333"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__TIMEOUT__TOTALSECONDS: "5"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__POLICY: "ConsecutiveFailures"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__HEALTHCHECK__ACTIVE__PATH: "/health"
      REVERSEPROXY__CLUSTERS__cluster_sogetec-admin__DESTINATIONS__destination1__ADDRESS: "https+http://sogetec-admin"
      REVERSEPROXY__CLUSTERS__cluster_keycloak__DESTINATIONS__destination1__ADDRESS: "http://keycloak"
      services__sogetec-api__http__0: "http://sogetec-api:${SOGETEC_API_PORT}"
      SOGETEC_API_HTTPS: "https://sogetec-api:${SOGETEC_API_PORT}"
      SOGETEC_FRONTEND_HTTP: "http://sogetec-frontend:8000"
      services__sogetec-frontend__http__0: "http://sogetec-frontend:8000"
      SOGETEC_FRONTEND_HTTPS: "https://sogetec-frontend:3000"
      SOGETEC_ADMIN_HTTP: "http://sogetec-admin:8001"
      services__sogetec-admin__http__0: "http://sogetec-admin:8001"
      SOGETEC_ADMIN_HTTPS: "https://sogetec-admin:3001"
      KEYCLOAK_HTTP: "http://keycloak:8080"
      services__keycloak__http__0: "http://keycloak:8080"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "gateway"
    expose:
      - "5000"
      - "443"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  sogetec.apphost-8ba8e719d3-keycloak-data:
    driver: "local"
