namespace Sogetec.Constants.Aspire;

public static class ParameterDescriptions
{
    public static class Keycloak
    {
        public const string Realm = """
            🔐 The Keycloak realm to use for authentication.
            This should match the realm configured in your Keycloak server.

            ⚠️  Important: The realm name is case-sensitive and must exist in your Keycloak instance.
            💡 Default value: 'master' (not recommended for production)
            📋 Example: 'Sogetec-realm' or 'production'

            📚 Resources:
            - For more information, visit: https://www.keycloak.org/docs/latest/server_admin/#_realms
            - To create a new realm, go to: https://www.keycloak.org/docs/latest/server_admin/#_creating_a_realm
            """;

        public const string ClientSecret = """
            🔑 The client secret for the Keycloak client used by the Sogetec application.
            This secret is required for confidential clients to authenticate with Keycloak.

            🔒 Security requirements:
            - Store securely and never commit to source control
            - Rotate regularly in production environments
            - Use Azure Key Vault or similar secret management solution

            ⚠️  Important: Only use for confidential clients (not public clients)
            💡 Format: Random string generated by Keycloak
            📋 Example: 'a1b2c3d4-5678-90ef-ghij-klmnopqrstuv'

            📚 Resources:
            - For more information, visit: https://www.keycloak.org/docs/latest/server_admin/#_clients
            - Secret management best practices: https://learn.microsoft.com/en-us/azure/key-vault/general/overview
            """;

        public const string Url = """
            🌐 The URL of the Keycloak server for authentication.
            This should be the base URL where your Keycloak instance is accessible.

            💡 Example: 'https://identity.Sogetec.com'
            ⚠️  Important: Must be accessible from the Sogetec application in production
            📋 Format: Must be a valid URL (including protocol)
            """;

        public const string DatabaseName = """
            🔑 The database name for the Keycloak server.
            """;

        public const string DatabaseUrl = """
            🔑 The database URL for the Keycloak server.
            """;

        public const string DatabaseUsername = """
            🔑 The database username for the Keycloak server.
            """;

        public const string DatabasePassword = """
            🔑 The database password for the Keycloak server.
            """;
    }

    public static class Redis
    {
        public const string ConnectionString = """
            🔴 The connection string for Redis cache.
            This is where your cache data is stored and accessed.

            💡 Example (local): 'localhost:6379'
            💡 Example (production): 'redis.Sogetec.com:6379'
            ⚠️  Important: Must be accessible from the Sogetec application in production
            📋 Format: 'hostname:port' or 'hostname:port,ssl=true'

            📚 Resources:
            - For more information, visit: https://redis.io/docs/connect/
            - Production best practices: https://redis.io/docs/management/admin/
            """;
    }

    public static class Cors
    {
        public const string SogetecSpa = """
            🌐 The URL of the Sogetec SPA application for CORS origin configuration.
            This is the customer-facing frontend URL that needs to be allowed to make cross-origin requests to backend APIs.

            💡 Example: 'https://acme.Sogetec.com'
            ⚠️  Important: Must include the protocol (https://) and match the exact origin used by the browser
            📋 Format: Must be a valid URL without trailing slash

            📚 Resources:
            - CORS documentation: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
            """;

        public const string SogetecAdminSpa = """
            🌐 The URL of the Sogetec Admin SPA application for CORS origin configuration.
            This is the admin-facing frontend URL that needs to be allowed to make cross-origin requests to backend APIs.

            💡 Example: 'https://admin.Sogetec.com'
            ⚠️  Important: Must include the protocol (https://) and match the exact origin used by the browser
            📋 Format: Must be a valid URL without trailing slash

            📚 Resources:
            - CORS documentation: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
            """;

        public const string SogetecBlogSpa = """
            🌐 The URL of the Sogetec Blog SPA application for CORS origin configuration.
            This is the blog frontend URL that needs to be allowed to make cross-origin requests to backend APIs.

            💡 Example: 'https://blog.Sogetec.com'
            ⚠️  Important: Must include the protocol (https://) and match the exact origin used by the browser
            📋 Format: Must be a valid URL without trailing slash

            📚 Resources:
            - CORS documentation: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
            """;
    }

    public static class Yarp
    {
        public const string Url = """
            🌐 The URL of the YARP (Yet Another Reverse Proxy) gateway.
            This is the main entry point for all frontend applications.

            💡 Example (local): 'http://localhost:8080'
            💡 Example (production): 'https://api.Sogetec.com'
            ⚠️  Important: Must be accessible from all frontend applications
            📋 Format: Must be a valid URL (including protocol)

            📚 Resources:
            - For more information, visit: https://microsoft.github.io/reverse-proxy/
            - Configuration guide: https://microsoft.github.io/reverse-proxy/config/
            """;
    }

    public static class ContainerRegistry
    {
        public const string Endpoint = """
            🌐 The endpoint URL of your container registry.
            This is where your container images are stored and accessed.

            💡 Example: 'ghcr.io'
            ⚠️  Important: Must be accessible from the Sogetec application in production
            📋 Format: Must be a valid URL (including protocol)
            """;

        public const string Repository = """
            📦 The name of the repository within your container registry.
            This is where your specific container images for Sogetec will be stored.

            💡 Example: 'yourorg/Sogetec'
            ⚠️  Important: Ensure the repository exists in your container registry
            📋 Format: Alphanumeric characters, dashes, and underscores only
            """;
    }

    public static class Postgres
    {
        public const string DB = """
            🌐 The endpoint URL or connection string of the database.
            This is where your the database is hosted and accessed.

            💡 Example: 'supabase.com'
            ⚠️  Important: Must be accessible from the Sogetec application in production
            📋 Format: Must be a valid connection string or URL
            """;
    }
}

